model:
  arch: unet
  encoder_name: seresnet50
  pretrained_from: fundus
  classes: 3

training:
  learning_rate: 0.003
  weight_decay: 0.0001

data:
  batch_size: 16
  num_workers: 8
  img_size: [512, 512]
  use_cache: true
  cache_option: duplicated_memory
  root:
    gave: /home/clement/Documents/data/GAVE/

trainer:
  max_epochs: 1000
  accelerator: gpu
  devices: [0, 1]
  check_val_every_n_epoch: 20