_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": Vessel Dice
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": val_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": AV Accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Vessel Accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": AV Jaccard
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Vessel Jaccard
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": AV Dice
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 48
                - 49
                - 55
                - 63
                - 74
                - 80
                - 103
                - 105
            "2":
                - 1
                - 9
                - 11
                - 41
                - 48
                - 49
                - 50
                - 55
                - 63
                - 74
                - 80
                - 103
                - 105
            "3":
                - 7
                - 16
                - 23
                - 55
                - 66
            "4": 3.11.9
            "5": 0.19.9
            "6": 4.44.2
            "8":
                - 2
                - 5
            "12": 0.19.9
            "13": linux-x86_64
arch:
    value: unet
classes:
    value: 3
data/batch_size:
    value: 16
data/cache_option:
    value: duplicated_memory
data/img_size:
    value:
        - 512
        - 512
data/num_workers:
    value: 8
data/root/drhagis:
    value: /home/clement/Documents/data/AV_Datasets/DRHAGIS/
data/root/fives-test:
    value: /home/clement/Documents/data/AV_Datasets/FIVES-test/
data/root/fives-train:
    value: /home/clement/Documents/data/AV_Datasets/FIVES-train/
data/root/gave:
    value: /home/clement/Documents/data/GAVE/
data/root/hrf:
    value: /home/clement/Documents/data/AV_Datasets/HRF/
data/root/idrid-reta:
    value: /home/clement/Documents/data/AV_Datasets/IDRID-RETA-train/
data/root/inspire:
    value: /home/clement/Documents/data/AV_Datasets/INSPIRE/
data/root/les:
    value: /home/clement/Documents/data/AV_Datasets/LES-AV/
data/root/maplesdr:
    value: /home/clement/Documents/data/AV_Datasets/MAPLES-DR/
data/use_cache:
    value: true
encoder_name:
    value: convnext_base
learning_rate:
    value: 0.003
model/arch:
    value: unet
model/classes:
    value: 3
model/encoder_name:
    value: convnext_base
model/pretrained_from:
    value: imagenet
pretrained_from:
    value: imagenet
trainer/accelerator:
    value: gpu
trainer/check_val_every_n_epoch:
    value: 20
trainer/devices:
    value:
        - 0
        - 1
trainer/max_epochs:
    value: 1000
training/learning_rate:
    value: 0.003
training/weight_decay:
    value: 0.0001
weight_decay:
    value: 0.0001
